Repository dachcom-digital/pimcore-formbuilder, pull requests merged in 2025-01, with the labels that each got.

#503 [ORM] use xml mapping, resolves #501
  config/doctrine/model/DoubleOptInSession.orm.xml
  config/doctrine/model/DoubleOptInSession.orm.yml
  config/doctrine/model/FormDefinition.orm.xml
  config/doctrine/model/FormDefinition.orm.yml
  config/doctrine/model/OutputWorkflow.orm.xml
  config/doctrine/model/OutputWorkflow.orm.yml
  config/doctrine/model/OutputWorkflowChannel.orm.xml
  config/doctrine/model/OutputWorkflowChannel.orm.yml
  src/FormBuilderBundle.php
  tests/Functional/Fields/AbstractFieldCest.php
  tests/Functional/Fields/DateTimeFieldCest.php
  tests/Functional/Fields/TimeFieldCest.php
Labels: enhancement

#500 [Feature] Bootstrap 5 layout support
  README.md
  config/install/translations/admin.csv
  config/pimcore/config.yaml
  docs/110_CustomTemplates.md
  templates/form/theme/bootstrap_5_horizontal_layout.html.twig
  templates/form/theme/bootstrap_5_layout.html.twig
  templates/form/theme/macro/bootstrap_5_horizontal_layout.html.twig
  templates/form/theme/macro/bootstrap_5_layout.html.twig
  tests/Functional/SimpleForm/SimpleFormEditWindowCest.php
  tests/Unit/Config/TemplateTest.php
Labels: new feature

#507 fix passing null value to preg_split
  UPGRADE.md
  src/OutputWorkflow/Channel/Email/Parser/MailParser.php
Labels: bug
